### ISSUE TITLE
US 1 - MVP- Content List

### ISSUE THREAD

**Issue by idontgitthiscode** [idontgitthiscode/keineahnungbre#2]
## Value proposition

As a user 
I want to be able to get overview of Web development Pages/resources
so that can be provided with the best web tools on the fly.

## Description

![Image](https://user-images.githubusercontent.com/62408854/258843890-5f208e31-cc56-48a4-8188-3803cdc3a79e.png)

## Acceptance criteria
- [x] must display at least one content-resource
- [x] must be reachable from web
- [x] content boxes need a description
- [x] content boxes need a picture
- [x] should be build mobile first

## Tasks
- [x] Create a new branch. 
- [x] Create content boxes
- [x] add images
- [x] add description
- [x] build mobile responsive
- [x] add to vercel for deployment
