### ISSUE TITLE
US1 -Content List

### ISSUE THREAD

**Issue by idontgitthiscode** [idontgitthiscode/keineahnungbre#2]
## Value proposition

As a user
I want to see content about web development 
so that I can have a quick overview of useful resources regarding this topic

## Description

![Image](https://user-images.githubusercontent.com/62408854/258233990-4b7487ea-676e-4c0f-a598-1edb0fd0b005.png)

## Acceptance criteria
- [ ] A list of Content is displayed to user
- [ ] Content should be about web development

## Tasks
- [ ] Create a new branch. 
- [ ] Create the component for the content list
- [ ] add the First content to our list
- [ ] setup react
